// Top-level build file where you can add configuration options common to all sub-projects/modules.

plugins {
    id 'com.android.application' version '7.4.1' apply false
    id 'com.android.library' version '7.4.1' apply false
    id 'org.jetbrains.kotlin.android' version "1.8.10" apply false
    id 'com.google.gms.google-services' version '4.3.15' apply false
    id 'com.google.firebase.crashlytics' version '2.9.4' apply false
    id 'com.google.dagger.hilt.android' version '2.44' apply false
}

ext {

    def scriptDir = "$rootProject.projectDir/scripts"

    scripts = [
            "android_test_dependency"        : "$scriptDir/android_test_dependency.gradle",
            "android_test_compose_dependency": "$scriptDir/android_test_compose_dependency.gradle",
            "test_dependency"                : "$scriptDir/test_dependency.gradle",
            "android_common"                 : "$scriptDir/android_common.gradle",
            "android_library"                : "$scriptDir/android_library.gradle",
            "versions"                       : "$scriptDir/versions.gradle",
    ]

    apply from: "$scripts.versions"


    compileSdk = 33
    minSdk = 26
    targetSdk = 33
    applicationId = "com.omar.retromp3recorder"
    kotlin_compiler = "1.4.3"
}
