pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}


rootProject.name = "retro-mp3"

include ':app'
include ':io-audioplayer'
include ':io-mp3recorder'
include ':io-audio-tansformer'
include ':io-share'
include ':storage'
include ':utils'
include ':ui-wavetable'
include ':usecases'
