pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}


rootProject.name = "retro-mp3"

include ':app'

include ':io:audioplayer'
include ':io:mp3recorder'
include ':io:audio-transformer'
include ':io:share'
include ':io:billing'
include ':io'

include ':data:storage'
include ':data:mock'

include ':utils:data'
include ':utils:platform'
include ':utlis'


include ':ui:wave-visualiser'
include ':ui:statebutton'
include ':ui:wavetable'
include ':ui:paging-column'
include ':ui:search-bar'
include ':ui'

include ':usecases'

include ':entity:data'
include ':entity:platform'
include ':entity'
