apply plugin: "kotlin"

dependencies {
    implementation "com.github.alkurop:ghostinshell:$versions.ghostinshell"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$versions.coroutines"
    implementation project(":entity:data")
}

compileKotlin {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11

}
