plugins {
    id "com.android.library"
    id "kotlin-android"
}

apply from: "$scripts.android_library"

android {
    namespace "${applicationId}.io"
}

dependencies {
    api project(':io:mp3recorder')
    api project(':io:audioplayer')
    api project(':io:share')
    api project(':io:audio-transformer')
    api project(':io:billing')
    api project(':io:speech-recognition')
    api project(':io:downloader')
}
