plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'kotlin-kapt'
}
apply from: "$scripts.android_library"

android {
    defaultConfig {
        javaCompileOptions {
            annotationProcessorOptions {
                arguments += [
                        "room.schemaLocation"  : "$projectDir/schemas".toString(),
                        "room.incremental"     : "true",
                        "room.expandProjection": "true"]
            }
        }
    }

    namespace "${applicationId}.data.storage"
}

apply from: "$scripts.test_dependency"

dependencies {
    implementation project(':entity')
    implementation project(':utils')
    implementation project(':io')

    implementation "com.github.alkurop:stringerbell:$versions.stringerbell"
    implementation "com.github.alkurop:ghostinshell:$versions.ghostinshell"

    implementation "androidx.room:room-runtime:$versions.room"
    implementation "androidx.room:room-ktx:$versions.room"
    kapt "androidx.room:room-compiler:$versions.room"

    api "androidx.paging:paging-runtime-ktx:$versions.paging"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-rx3:$versions.rxCoroutines"

    implementation "com.google.dagger:hilt-android:$versions.hilt"
    kapt "com.google.dagger:hilt-compiler:$versions.hilt"

    constraints {
        implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:$versions.lifecycle") {
            because 'Because of confliciting versions we have a failing circle ci'
        }
    }

    testImplementation project(':data:mock')

}

