plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

apply from: "$scripts.android_library"

android {
    namespace "${applicationId}.ui.wavetable"
    buildFeatures {
        compose true
    }
}

dependencies {

    implementation project(':utils')
    implementation project(':entity')

    implementation "androidx.core:core-ktx:$versions.coreKtx"

    def composeBom = platform("androidx.compose:compose-bom:$versions.compose_bom")

    implementation composeBom

    implementation "androidx.compose.ui:ui"
    implementation "androidx.compose.material3:material3"
    implementation "androidx.compose.ui:ui-tooling-preview"
    debugImplementation "androidx.compose.ui:ui-tooling"
    debugImplementation "androidx.compose.ui:ui-test-manifest"

    debugImplementation "androidx.compose.ui:ui-tooling"
    debugImplementation "androidx.compose.ui:ui-test-manifest"
}
