plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}
apply from: "$scripts.android_library"

android {
    namespace "${applicationId}.ui.wavevisualiser"
}

dependencies {
    implementation "androidx.core:core-ktx:$versions.coreKtx"
    implementation "io.reactivex.rxjava3:rxandroid:$versions.rxAndroid"
}
