plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
}

android {

    compileSdk rootProject.ext.compileSdk

    defaultConfig {
        applicationId "com.omar.retromp3recorder.app"
        testApplicationId "com.omar.retromp3recorder.app.test"

        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdk
        versionCode 371
        versionName "3.71"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        signingConfig signingConfigs.debug
    }

    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion '1.3.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            minifyEnabled false
            debuggable true
        }
    }

    signingConfigs {
        debug {
            storeFile file('../debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    namespace 'com.omar.retromp3recorder.app'
}

dependencies {
    implementation "androidx.appcompat:appcompat:$versions.support"
    implementation "androidx.recyclerview:recyclerview:$versions.recyclerView"
    implementation "com.android.support.constraint:constraint-layout:$versions.constraintLayout"
    implementation "com.squareup.picasso:picasso:$versions.picasso"
    implementation "com.github.alkurop:stringerbell:$versions.stringerbell"
    implementation "com.jakewharton.rxbinding4:rxbinding:$versions.rxView"
    implementation "com.github.alkurop:Android-Runtime-Permission-Manager:$versions.permission"
    implementation "androidx.fragment:fragment-ktx:$versions.ktxFragment"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$versions.lifecycle"
    implementation "com.github.alkurop:ghostinshell:$versions.ghostinshell"
    implementation "com.github.alkurop:RangeBar:$versions.rangeBar"

    implementation "androidx.compose.ui:ui:$versions.compose"
    implementation "androidx.compose.ui:ui-tooling:$versions.compose"
    implementation "androidx.navigation:navigation-compose:$versions.composeNav"
    implementation "androidx.compose.foundation:foundation:$versions.compose"
    implementation "androidx.paging:paging-compose:$versions.composePaging"
    implementation "androidx.lifecycle:lifecycle-viewmodel-compose:$versions.composeViewModel"
    implementation "androidx.compose.runtime:runtime-rxjava3:$versions.compose"
    implementation "com.google.accompanist:accompanist-appcompat-theme:0.25.1"
    implementation "androidx.compose.material:material:$versions.compose"
    implementation "androidx.constraintlayout:constraintlayout-compose:$versions.composeConstraint"
    implementation "com.google.android.material:material:$versions.material"

    implementation "com.google.dagger:dagger:$versions.dagger"
    kapt "com.google.dagger:dagger-compiler:$versions.dagger"

    implementation project(':utils')
    implementation project(':io-mp3recorder')
    implementation project(':io-audioplayer')
    implementation project(':io-audio-tansformer')
    implementation project(':io-share')
    implementation project(':ui-wavetable')
    implementation project(':usecases')
    implementation project(':storage')

    // Import the BoM for the Firebase platform
    implementation platform("com.google.firebase:firebase-bom:$versions.firebase")

    // Declare the dependencies for the Crashlytics and Analytics libraries
    // When using the BoM, you don't specify versions in Firebase library dependencies
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'

    androidTestImplementation "androidx.test.espresso:espresso-core:$testVersions.espressoCore"
    androidTestImplementation "androidx.test:runner:$testVersions.espresso"
    androidTestImplementation "androidx.test:rules:$testVersions.espresso"
    androidTestImplementation "androidx.test.ext:junit-ktx:$testVersions.junitKtx"

}
