plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
}

android {

    compileSdk rootProject.ext.compileSdk

    defaultConfig {
        applicationId "com.omar.retromp3recorder.app"
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdk
        versionCode 321
        versionName "3.21"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        signingConfig signingConfigs.debug
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            minifyEnabled false
            debuggable true
        }
    }

    signingConfigs {
        debug {
            storeFile file('../debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:$versions.support"
    implementation "androidx.recyclerview:recyclerview:$versions.recyclerView"
    implementation "com.android.support.constraint:constraint-layout:$versions.constraintLayout"
    implementation "com.squareup.picasso:picasso:$versions.picasso"
    implementation "com.github.alkurop:stringerbell:$versions.stringerbell"
    implementation "com.jakewharton.rxbinding4:rxbinding:$versions.rxView"
    implementation "com.github.alkurop:Android-Runtime-Permission-Manager:$versions.permission"
    implementation "androidx.fragment:fragment-ktx:$versions.ktxFragment"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$versions.lifecycle"
    implementation "com.github.alkurop:ghostinshell:$versions.ghostinshell"

    implementation "com.google.dagger:dagger:$versions.dagger"
    kapt "com.google.dagger:dagger-compiler:$versions.dagger"

    implementation project(':utils')
    implementation project(':io-mp3recorder')
    implementation project(':io-audioplayer')
    implementation project(':io-share')
    implementation project(':ui-state-button')
    implementation project(':ui-wavetable')
    implementation project(':usecases')
    implementation project(':storage')

    // Import the BoM for the Firebase platform
    implementation platform("com.google.firebase:firebase-bom:$versions.firebase")

    // Declare the dependencies for the Crashlytics and Analytics libraries
    // When using the BoM, you don't specify versions in Firebase library dependencies
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'
}
