plugins {
    id 'com.android.library'
    id 'kotlin-android'
}
apply from :"$scripts.android_library"

android {
    namespace "${applicationId}.usecase"
}

apply from: "$scripts.test_dependency"

dependencies {
    implementation "androidx.appcompat:appcompat:$versions.support"

    implementation project(':utils')
    testImplementation project(':data:mock')

    api project(':entity')
    api project(':io')
    api project(':data')

    implementation "com.google.dagger:hilt-android:$versions.hilt"
    implementation "com.github.alkurop:ghostinshell:$versions.ghostinshell"
    implementation "com.github.alkurop:stringerbell:$versions.stringerbell"
}
