plugins {
    id 'com.android.library'
    id 'kotlin-android'
}
apply from :"$scripts.android_library"

android {
    namespace "${applicationId}.usecase"
}

apply from: "$scripts.test_dependency"

dependencies {
    implementation "androidx.appcompat:appcompat:$versions.support"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-rx3:$versions.rxCoroutines"

    implementation project(':utils:platform')
    implementation project(':utils:domain')
    testImplementation project(':data:mock')

    implementation project(':entity:platform')
    implementation project(':io:mp3recorder')
    implementation project(':io:audioplayer')
    implementation project(':io:audio-tansformer')
    implementation project(':io:share')
    implementation project(':data:storage')

    implementation "com.google.dagger:hilt-android:$versions.hilt"
    implementation "com.github.alkurop:ghostinshell:$versions.ghostinshell"
    implementation "com.github.alkurop:stringerbell:$versions.stringerbell"
}
