plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'kotlin-kapt'
}

android {
    compileSdk rootProject.ext.compileSdk

    defaultConfig {
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdk
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    namespace 'com.omar.retromp3recorder.app.utils'
}

dependencies {
    api "org.jetbrains.kotlin:kotlin-stdlib:${versions.kotlin}"
    api "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${versions.kotlin}"
    api "io.reactivex.rxjava3:rxjava:$versions.rxJava"
    api "io.reactivex.rxjava3:rxkotlin:$versions.rxKotlin"
    api "io.reactivex.rxjava3:rxandroid:$versions.rxAndroid"

    api "com.jakewharton.timber:timber:$versions.timber"
    api "com.github.lincollincol:amplituda:$versions.amplituda"

    implementation "com.google.dagger:dagger:$versions.dagger"
    kapt "com.google.dagger:dagger-compiler:$versions.dagger"

    implementation "com.github.alkurop:ghostinshell:$versions.ghostinshell"
    implementation "com.google.dagger:dagger:$versions.dagger"
    implementation "androidx.appcompat:appcompat:$versions.support"
    implementation "com.mpatric:mp3agic:$versions.mp3magic"
    implementation "com.github.alkurop:stringerbell:$versions.stringerbell"
}
