android {
    compileSdk rootProject.ext.compileSdk

    defaultConfig {
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdk
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    composeOptions {
        kotlinCompilerExtensionVersion = rootProject.ext.kotlin_compiler
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    packagingOptions {
        resources.excludes.add("META-INF/*")
    }
    kotlinOptions {
        // Treat all Kotlin warnings as errors
        freeCompilerArgs += '-opt-in=kotlin.RequiresOptIn'
        jvmTarget = '17'
    }

}
