dependencies {

    androidTestImplementation "androidx.test.ext:junit:$versions.android_junit"

    androidTestImplementation "androidx.test.espresso:espresso-contrib:$versions.espresso"
    androidTestImplementation "androidx.test.espresso:espresso-core:$versions.espresso"
    androidTestImplementation "androidx.arch.core:core-testing:$versions.core_testing"
    androidTestImplementation "com.google.truth:truth:$versions.truth"

    androidTestImplementation "io.mockk:mockk-android:${versions.mockk}"

    androidTestImplementation "app.cash.turbine:turbine:$versions.turbine"
    androidTestImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$versions.coroutines"
}
