dependencies {
    testImplementation "app.cash.turbine:turbine:$versions.turbine"
    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$versions.coroutines"
    testImplementation "io.mockk:mockk:$versions.mockk"
    testImplementation "junit:junit:$versions.junit"
    testImplementation "com.google.truth:truth:$versions.truth"
}
