plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

apply from: "$scripts.android_library"

android {
    namespace "${applicationId}.utils.domain"
}

dependencies {

    implementation project(":domain:platform")

    api project(':utils:generic')
    api project(':utils:platform')
    api "io.reactivex.rxjava3:rxjava:$versions.rxJava"
    api "io.reactivex.rxjava3:rxkotlin:$versions.rxKotlin"
    api "io.reactivex.rxjava3:rxandroid:$versions.rxAndroid"

    api "com.jakewharton.timber:timber:$versions.timber"
    api "com.github.lincollincol:amplituda:$versions.amplituda"

    implementation "com.google.dagger:dagger:$versions.dagger"

    implementation "com.github.alkurop:ghostinshell:$versions.ghostinshell"
    implementation "com.mpatric:mp3agic:$versions.mp3magic"
    implementation "androidx.appcompat:appcompat:$versions.support"
    implementation "com.github.alkurop:stringerbell:$versions.stringerbell"
}
