plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

android {
    compileSdk rootProject.ext.compileSdk

    defaultConfig {
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdk
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    namespace 'com.omar.retromp3recorder.ui.wavetable'
}

dependencies {
    implementation project(':utils')
    implementation "com.android.support.constraint:constraint-layout:$versions.constraintLayout"
    implementation "androidx.appcompat:appcompat:$versions.support"
}
