plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'kotlin-kapt'
}

apply from: "$scripts.android_library"

android {
    namespace "${applicationId}.io.speech"
}

dependencies {
    implementation project(':utils')
    implementation project(':entity')
    implementation "com.github.alkurop:stringerbell:$versions.stringerbell"
    implementation "com.google.dagger:hilt-android:$versions.hilt"
    kapt "com.google.dagger:hilt-compiler:$versions.hilt"
}
